### ISSUE TITLE
Investigate "Task exception was never retrieved" errors

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#2348]
## Bug Description
While working on some new code, I introduced a minor error in my branch. When I ctrl-c'd connectors to fix the mistake before retrying, I noticed an error line of:
```
Task exception was never retrieved
```
showed up, followed by a _different_ stack trace. At first I didn't pay much attention, but when I restarted my connector a few minutes later, neither of those errors were displayed as the reason for the job failure. Instead, I had:
```
The job has not seen any update for some time..
```
This makes me worry that there's a part of our code where we're not appropriately handling async errors, and are just leaving jobs in "In progress" even though they definitely failed.

<details><summary>relevant logs</summary>

```
[FMWK][12:52:44][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: ViJjr44BK4iIzr6Zk8wO] Sync progress -- created: 0 | updated: 0 | deleted: 0
[FMWK][12:52:44][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: ViJjr44BK4iIzr6Zk8wO] Fetching messages between 2024-04-02 17:52:38.062500 and 2024-04-05 17:52:38.062500 from channel: 'search-extract-and-transform'
[FMWK][12:52:46][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: ViJjr44BK4iIzr6Zk8wO] Sync progress -- created: 100 | updated: 0 | deleted: 0
[FMWK][12:54:28][ERROR] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: ViJjr44BK4iIzr6Zk8wO] 'indexed_document_volume'
Traceback (most recent call last):
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py", line 208, in execute
    await self._sync_done(sync_status=sync_status, sync_error=fetch_error)
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py", line 353, in _sync_done
    else self.sync_orchestrator.ingestion_stats()
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 874, in ingestion_stats
    stats[INDEXED_DOCUMENT_VOLUME] / (1024 * 1024)
KeyError: 'indexed_document_volume'
[FMWK][12:54:28][ERROR] Exception found for task Task-89: 'indexed_document_volume'
NoneType: None
^C[FMWK][12:55:54][INFO] Caught SIGINT. Graceful shutdown.
[FMWK][12:55:54][INFO] Bye
Task exception was never retrieved
future: <Task finished name='Task-102' coro=<SyncJobRunner.update_ingestion_stats() done, defined at /Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py:493> exception=KeyError('indexed_document_volume')>
Traceback (most recent call last):
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py", line 500, in update_ingestion_stats
    result = self.sync_orchestrator.ingestion_stats()
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 874, in ingestion_stats
    stats[INDEXED_DOCUMENT_VOLUME] / (1024 * 1024)
KeyError: 'indexed_document_volume'
Task exception was never retrieved
future: <Task finished name='Task-101' coro=<Sink.run() done, defined at /Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py:315> exception=ValueError('too many values to unpack (expected 2)')>
Traceback (most recent call last):
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 317, in run
    await self._run()
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 385, in _run
    await self._batch_bulk(batch, stats)
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/logger.py", line 196, in _awrapped
    return await func(*args, **kw)
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 190, in _batch_bulk
    ids_to_ops = self._map_id_to_op(operations)
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 213, in _map_id_to_op
    for op, doc in entry:
ValueError: too many values to unpack (expected 2)
```

</details>

My current theory is that errors that occur in the `bulk_tasks` pool or in `_batch_bulk` specifically are not being handled correctly. These types of errors _should_ be uncommon, but that doesn't mean we don't have a bug.

### To Reproduce
Needs testing, but I expect just adding a `raise` in `_batch_bulk` would reproduce

## Expected behavior
If a sync job fails with a stack trace in our logs, that same error should be present in kibana and the job should be failed near-immediately.

## Environment
8.14.0.0-SNAPSHOT (main, maybe a few days old)

**Comment by vidok** [comment]
Isn't this just this error? 

```
Traceback (most recent call last):
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py", line 208, in execute
    await self._sync_done(sync_status=sync_status, sync_error=fetch_error)
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/sync_job_runner.py", line 353, in _sync_done
    else self.sync_orchestrator.ingestion_stats()
  File "/Users/seanstory/Desktop/Dev/connectors-python/connectors/es/sink.py", line 874, in ingestion_stats
    stats[INDEXED_DOCUMENT_VOLUME] / (1024 * 1024)
KeyError: 'indexed_document_volume'
```

So there 2 errors in the source code. 
`KeyError: 'indexed_document_volume'` that caused `ValueError: too many values to unpack (expected 2)`.

**Comment by seanstory** [comment]
https://github.com/elastic/connectors/issues/2353 looks similar.

> KeyError: 'indexed_document_volume' that caused ValueError: too many values to unpack (expected 2)

These were two distinct issues in my local changes. I don't think one was caused by the other.

**Comment by seanstory** [comment]
There's definitely something off here. I just edited `_batch_bulk` on `main` to raise an error straight off:
```
diff --git a/connectors/es/sink.py b/connectors/es/sink.py
index 2779011f..d785cb74 100644
--- a/connectors/es/sink.py
+++ b/connectors/es/sink.py
@@ -149,6 +149,8 @@ class Sink:
 
     @tracer.start_as_current_span("_bulk API call", slow_log=1.0)
     async def _batch_bulk(self, operations, stats):
+
+        raise Exception("I think this will reproduce")
         # TODO: make this retry policy work with unified retry strategy
         @retryable(retries=self.max_retires, interval=self.retry_interval)
         async def _bulk_api_call():
```

And the job didn't fail. It just didn't index anything.

<img width="891" alt="Screenshot 2024-04-08 at 2 22 46 PM" src="https://github.com/elastic/connectors/assets/5288246/b84767c9-c493-4315-acba-d401990c14f7">


Despite what the logs have to say:
```
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] Sync ended with status completed -- created: 41 | updated: 1 | deleted: 102 (took 58 seconds)
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] --- Counters ---
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'attachment_extracted' : 0
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'bulk_operations' : {'index': 42, 'delete': 102}
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'deleted_document_count' : 0
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'doc_created' : 41
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'doc_deleted' : 102
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'doc_updated' : 1
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'indexed_document_count' : 0
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] 'indexed_document_volume' : 0
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] full counters dictionary: {'doc_created': 41, 'attachment_extracted': 0, 'doc_updated': 1, 'doc_deleted': 102, 'bulk_operations': {'index': 42, 'delete': 102}, 'indexed_document_count': 0, 'indexed_document_volume': 0, 'deleted_document_count': 0}
[FMWK][14:20:09][INFO] [Connector id: TCAXpY4BS_YGsI0Kbufn, index name: slack, Sync job id: IBomv44Btb0Ua5HOD3N-] ----------------
```

**Comment by seanstory** [comment]
I poked at this for a bit today. I got the job to fail _at the end_ but something's not working about getting it to fail the first time it hits an error. WIP PR: https://github.com/elastic/connectors/pull/2364

**Comment by artem-shelkovnikov** [comment]
Dunno if it helps, but here's my way of looking at it:

1. Somebody CTRL+C. What it does is it immediately moves execution to https://github.com/elastic/connectors/blob/main/connectors/service_cli.py#L133
2. Multiservice class starts [the shutdown](https://github.com/elastic/connectors/blob/main/connectors/services/base.py#L181) and stops execution service, which in turn tries to [stop the execution pool](https://github.com/elastic/connectors/blob/main/connectors/services/job_execution.py#L34)
3. Sync job pool tries to [cancel all the tasks](https://github.com/elastic/connectors/blob/main/connectors/utils.py#L472) that are running inside
4. This causes `asyncio.CancelledError` which is [caught by the job executor](https://github.com/elastic/connectors/blob/main/connectors/sync_job_runner.py#L197) and it, in turn, starts cancelling[ job orchestrator](https://github.com/elastic/connectors/blob/main/connectors/sync_job_runner.py#L328) and here the fun starts

Cancellation happens asynchronously from here on, meaning that for each `await` execution moves somewhere else, and my assumption now is that during cancellation some of the code is working while it should be stopped (order of cancellation is broken)

5. Then sync orchestrator [starts the cancellation](https://github.com/elastic/connectors/blob/main/connectors/es/sink.py#L781) and already here I'm wondering: sink is closed first, while extractor still attempts to put documents into the queue - can this cause problems?

**Comment by artem-shelkovnikov** [comment]
Actually I think the problem is [here](https://github.com/elastic/connectors/blob/main/connectors/sync_job_runner.py#L328-L336):

```
    async def _sync_done(self, sync_status, sync_error=None):
        if self.sync_orchestrator is not None and not self.sync_orchestrator.done():
            await self.sync_orchestrator.cancel()
        if self.job_reporting_task is not None and not self.job_reporting_task.done():
            self.job_reporting_task.cancel()
            try:
                await self.job_reporting_task
            except asyncio.CancelledError:
                self.sync_job.log_debug("Job reporting task is stopped.")
```

Stats update task should intuitively be closed before the `sync_orchestrator` is cancelled, cause stats update task relies on `sync_orchestrator` internally. Theoretically, swapping these two resource release statements should fix it.

That also explains the problem - your sync was supposed to be put into "suspended" state but failed because the stats update task failed. Then [this code](https://github.com/elastic/connectors/blob/main/connectors/sync_job_runner.py#L331-L336) will raise an error and sync will not be put into "suspended" state, therefore causing an orphan sync.

This should be provable with unit test, I think.

**Comment by seanstory** [comment]
That does seem to fix the `Task exception was never retrieved` part. But still doesn't address that the sync isn't failing when the Sink class is totally hosed and just raising errors.
